"""change field from type to type_id

Revision ID: 21db79ab3578
Revises: 495da0fd3962
Create Date: 2025-05-31 14:57:38.530427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21db79ab3578'
down_revision: Union[str, None] = '495da0fd3962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=False))
        batch_op.drop_column('type')
    op.create_foreign_key('package_package_type_FK', 'package',
                          'package_type', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('package_package_type_FK', 'package', type_='primary')
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
