"""setup database

Revision ID: 2c58313f027e
Revises: 
Create Date: 2025-06-02 21:11:43.813972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c58313f027e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('content_value_usd', sa.Float(), nullable=False),
    sa.Column('session_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('delivery_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['package_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO package_type(type_name) values ('одежда')")
    op.execute("INSERT INTO package_type(type_name) values ('электроника')")
    op.execute("INSERT INTO package_type(type_name) values ('разное')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    op.drop_table('package_type')
    # ### end Alembic commands ###
