"""initial

Revision ID: 7a94223c5daf
Revises: 
Create Date: 2025-05-30 02:25:03.799153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.packages import PackageTypeTable

# revision identifiers, used by Alembic.
revision: str = '7a94223c5daf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(200), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('type', sa.Enum(PackageTypeTable.clothes, PackageTypeTable.electronics, PackageTypeTable.other),
                              nullable=False),
                    sa.Column('content_value_usd', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    # ### end Alembic commands ###
