"""added table package type

Revision ID: f6749c7cca67
Revises: 7a94223c5daf
Create Date: 2025-05-31 00:21:07.449772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6749c7cca67'
down_revision: Union[str, None] = '7a94223c5daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('одежда', 'электроника', 'разное'),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=200),
               type_=mysql.ENUM('одежда', 'электроника', 'разное'),
               existing_nullable=False)

    op.drop_table('package_type')
    # ### end Alembic commands ###
