from environs import Env

env = Env()
env.read_env()

DATABASE_USER = env.str("DATABASE_USER")
DATABASE_PASSWORD = env.str("DATABASE_PASSWORD")
DATABASE_HOST = env.str("DATABASE_HOST")
DATABASE_NAME = env.str("DATABASE_NAME")
DATABASE_PORT = env.str("DATABASE_PORT")
DATABASE_URL = f"mysql+aiomysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
